language: python

matrix:
    include:
        - dist: xenial
          sudo: true
          python: 3.9
        - dist: xenial
          sudo: true
          python: 3.7

install:
  - pip install poetry
  - poetry install

script: poetry run pytest
